---
name: Auto update PR's

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.9.1
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN || secrets.GITHUB_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: true
          require_auto_merge_enabled: false
          sort: 'created'
          direction: 'desc'
